# Generated by Django 5.1.5 on 2025-01-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
