# Generated by Django 5.1.5 on 2025-01-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='porfolio/images/')),
                ('nombre', models.CharField(max_length=50)),
                ('perfilOcupaciona', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
