# Generated by Django 5.1.5 on 2025-01-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0003_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(upload_to='porfolio/imagesPerfil/'),
        ),
    ]
